# .github/workflows/deploy.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest
      # non sono riuscito a scrivere i test, da aggiungere in un secondo momento
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-south-1'

      - name: Build with SAM
        run: |
          sam build

      - name: Deploy with SAM
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name fastapi-meteo-app-stack --capabilities CAPABILITY_IAM
